name: route_gen
description: Route Generator for nomo_router
version: 0.1.1
repository: https://github.com/dev2-nomo/route-gen

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  source_gen: ^2.0.0
  collection: ^1.19.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
